import React from 'react';
import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { useMvpPlan } from '../contexts/MvpPlanContext';
import sdk from '@stackblitz/sdk';
import JSZip from 'jszip';
import type { MvpPlan } from '../types';
import { generateFixInstructions } from '../services/geminiService';
import Alert from '../components/common/Alert';

const PreviewPage: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    const { getPlanById, updatePlan } = useMvpPlan();
    const navigate = useNavigate();
    const [plan, setPlan] = useState<MvpPlan | null>(null);
    const [isZipping, setIsZipping] = useState(false);
    const embedRef = useRef<HTMLDivElement>(null);

    // Manual-fix state
    const [isFetchingInstructions, setIsFetchingInstructions] = useState(false);
    const [fixInstructions, setFixInstructions] = useState<string | null>(null);
    const [fixError, setFixError] = useState<string | null>(null);
    const [userProvidedError, setUserProvidedError] = useState('');

    useEffect(() => {
        if (id) {
            const foundPlan = getPlanById(id);
            if (foundPlan?.generatedCode) {
                setPlan(foundPlan);
            } else {
                navigate(foundPlan ? `/view-plan/${id}` : '/dashboard');
            }
        }
    }, [id, getPlanById, navigate]);
    
    useEffect(() => {
        if (!embedRef.current || !plan?.generatedCode) return;

        embedRef.current.innerHTML = '';

        const projectFiles = plan.generatedCode.reduce((acc, file) => {
            const path = file.path.startsWith('/') ? file.path.substring(1) : file.path;
            acc[path] = file.content;
            return acc;
        }, {} as Record<string, string>);

        sdk.embedProject(
            embedRef.current,
            {
                title: plan.ideaPrompt || 'MVP Project',
                description: 'A project generated by MVPGen AI.',
                template: 'node',
                files: projectFiles,
            },
            {
                openFile: 'src/App.tsx',
                view: 'preview',
                theme: 'dark',
                height: '100%',
                hideExplorer: true,
            }
        );

    }, [plan]);
    
    const handleGetFixInstructions = async () => {
        if (!plan?.generatedCode || isFetchingInstructions || !userProvidedError.trim()) return;

        setIsFetchingInstructions(true);
        setFixInstructions(null);
        setFixError(null);

        try {
            const instructions = await generateFixInstructions(plan.generatedCode, userProvidedError);
            setFixInstructions(instructions);
        } catch (err: any) {
            console.error("Failed to get fix instructions:", err);
            setFixError(err.message || "An unexpected error occurred while generating fix instructions.");
        } finally {
            setIsFetchingInstructions(false);
        }
    };


    const handleDownloadZip = async () => {
        if (!plan?.generatedCode) return;
        setIsZipping(true);
        try {
            const zip = new JSZip();
            plan.generatedCode.forEach(file => {
                zip.file(file.path.startsWith('/') ? file.path.substring(1) : file.path, file.content);
            });
            const blob = await zip.generateAsync({ type: 'blob' });
            const link = document.createElement('a');
            link.href = URL.createObjectURL(blob);
            const safeFilename = (plan.ideaPrompt || 'idea').toLowerCase().replace(/[^a-z0-9]/g, '-').substring(0, 30);
            link.download = `mvp-code-${safeFilename}.zip`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(link.href);
        } catch (error) {
            console.error("Failed to generate zip file", error);
            alert("An error occurred while creating the ZIP file.");
        } finally {
            setIsZipping(false);
        }
    };

    if (!plan) {
        return <div className="text-center py-10">Loading Project Preview...</div>;
    }

    if (!plan.generatedCode) {
         return (
            <div className="text-center py-10">
                <h2 className="text-2xl font-bold mb-4">Code Not Generated Yet</h2>
                <p className="text-on-surface-variant mb-6">The code for this project hasn't been generated. Please go back to the plan viewer to generate it.</p>
                <Link to={`/view-plan/${id}`} className="px-6 py-2 text-sm bg-primary text-white rounded-md hover:bg-primary/90">
                    Back to Plan Viewer
                </Link>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <header>
                 <Link to={`/view-plan/${id}`} className="text-sm text-primary hover:underline">&larr; Back to Plan Details</Link>
                 <div className="flex flex-wrap justify-between items-center mt-2 gap-4">
                    <div>
                        <h1 className="text-3xl font-bold">Project Preview</h1>
                        <p className="text-on-surface-variant">Interact with your live project preview below.</p>
                    </div>
                 </div>
            </header>

            <section className="bg-surface p-6 rounded-lg shadow-lg">
                <h2 className="text-xl font-semibold text-on-surface">Get Help Fixing Errors</h2>
                <p className="text-sm text-on-surface-variant mt-2 mb-4">
                    If your project preview is showing an error, copy the error message from the console and paste it below. Our AI will provide instructions on how to fix it manually in the code editor.
                </p>

                {fixError && <div className="my-4"><Alert type="error" title="Failed to get Instructions" message={fixError} onClose={() => setFixError(null)} /></div>}
                
                <div className="flex flex-col sm:flex-row items-start gap-4">
                    <textarea
                        value={userProvidedError}
                        onChange={(e) => setUserProvidedError(e.target.value)}
                        className="flex-grow w-full h-24 p-3 border border-gray-600 bg-gray-700 text-on-surface rounded-md focus:ring-2 focus:ring-primary focus:border-primary transition placeholder-gray-400 text-sm"
                        placeholder="e.g., Error: Cannot find module 'lucide-react' or its corresponding type declarations."
                        disabled={isFetchingInstructions}
                        aria-label="Paste error message here"
                    />
                    <button
                        onClick={handleGetFixInstructions}
                        disabled={isFetchingInstructions || !userProvidedError.trim()}
                        className="w-full sm:w-auto px-4 py-2 text-sm font-medium rounded-md transition-colors flex items-center justify-center gap-2 bg-secondary text-white hover:bg-secondary/90 disabled:bg-gray-500 disabled:cursor-not-allowed"
                        title="Get AI-powered instructions to fix the error"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0 3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
                        {isFetchingInstructions ? 'Getting Instructions...' : 'Get Fix Instructions'}
                    </button>
                </div>
                {fixInstructions && (
                    <div className="mt-6 bg-background p-4 rounded-md border border-gray-700">
                        <h3 className="text-lg font-semibold text-on-surface mb-3">AI-Generated Fix Instructions</h3>
                        <div 
                            className="prose prose-sm prose-invert max-w-none text-on-surface-variant whitespace-pre-wrap"
                            dangerouslySetInnerHTML={{
                                __html: fixInstructions
                                    .replace(/### (.*)/g, '<h3 class="text-on-surface font-semibold mt-4 mb-2">$1</h3>')
                                    .replace(/```json\n([\s\S]*?)```/g, '<pre class="bg-gray-800 p-3 rounded-md text-sm"><code>$1</code></pre>')
                                    .replace(/`([^`]+)`/g, '<code class="bg-gray-700 rounded px-1 py-0.5 text-sm">$1</code>')
                            }}
                        />
                    </div>
                )}
            </section>

            <div ref={embedRef} className="rounded-lg overflow-hidden shadow-2xl border border-gray-700 h-[70vh]" />

            <section className="bg-surface p-8 rounded-lg shadow-lg">
                <h2 className="text-2xl font-semibold text-on-surface mb-2 text-center">Export Project</h2>
                <p className="text-center text-on-surface-variant mb-6">Download a ZIP file of the complete project source code.</p>
                <div className="flex justify-center">
                    <button onClick={handleDownloadZip} disabled={isZipping} className="w-full sm:w-auto px-8 py-3 bg-primary text-white rounded-lg flex items-center justify-center gap-2 hover:bg-primary/90 transition-colors disabled:bg-gray-500">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                        {isZipping ? 'Zipping...' : 'Download Project ZIP'}
                    </button>
                </div>
            </section>
        </div>
    );
};

export default PreviewPage;
